name: terratest

on:
  pull_request:
    branches:
      - main

jobs:
  terratest:
    runs-on: ubuntu-latest
    env:
      EXCLUDED_DIRS: ".github test" #space-delimited list for multiple exclusions
      TEST_PATH: "test"
      TEST_FILE: "tf_test.go"

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Get base dir
      run: |
        base_dir=$(pwd)
        echo "base_dir=$base_dir" >> $GITHUB_ENV

    - name: Get changed dir
      id: changed-dir
      run: |
        changed_dirs=$(git diff --name-only origin/${{ github.event.pull_request.base.ref }} origin/${{ github.event.pull_request.head.ref }} | xargs dirname | sort | uniq)
        for dir in $EXCLUDED_DIRS; do
          changed_dirs=$(echo "$changed_dirs" | grep -v "^$dir")
        done
        echo $changed_dirs >> changed_dirs.txt
    - run: cat $changed_dirs       
    # - name: Run Terratest
    #   run: |
    #     cd ${{ env.base_dir }}/$TEST_PATH/
    #     for dir in ${{ env.changed_dirs }}; do
    #       cd ${{ env.base_dir }}/$dir
    #       go test -v ${{ env.base_dir }}/$TEST_PATH/$TEST_FILE
    #     done
