name: terratest

on:
  push:
    branches:
    - main
  pull_request:
    branches:
      - main

jobs:
  terratest:
    runs-on: ubuntu-latest
    env:
      EXCLUDED_DIRS: ".github test" #space-delimited list for multiple exclusions
      TEST_PATH: "test"
      TEST_FILE: "tf_test.go"

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Get base dir
      run: |
        base_dir=$(pwd)
        echo "base_dir=$base_dir" >> $GITHUB_ENV

    - name: Get changed dir
      id: changed-dir
      run: |
        changed_dirs=$(git diff --name-only origin/${{ github.event.repository.default_branch }} origin/${{ github.head_ref }} | xargs dirname | sort | uniq)
        for dir in $EXCLUDED_DIRS; do
          changed_dirs=$(echo "$changed_dirs" | grep -v "^$dir")
        done
        echo $changed_dirs
        echo "changed_dirs=$changed_dirs" >> $GITHUB_ENV
       
    - name: Run Terratest
      run: |
        cd ${{ env.base_dir }}/$TEST_PATH/
        go mod download
        for dir in ${{ env.changed_dirs }}; do
          cd ${{ env.base_dir }}/$dir
          terraform init
          pwd
          go test -v ${{ env.base_dir }}/$TEST_PATH/$TEST_FILE >> ${{ env.base_dir }}/$dir/terratest.txt
        done
